[fan]
# threshold in °C, above fan goes to 25%, below turned off
lv0 = 30
# threshold in °C, above fan goes to 50% 
lv1 = 40 
# threshold in °C, above fan goes to 75% 
lv2 = 45
# threshold in °C, above fan goes to 100% 
lv3 = 50
# linearily interpolating speed between lv0 and lv3. ignoring lv1 and lv2.
linear = true 
# maximum relative fan speed in silence period, in float or percent with escape character, like so: 40%%
silentmaxlv = 0%%
# local start time (format: '%H:%M') of silence period
silentstart = 21:00 
# local end time (format: '%H:%M') of silence period
silentend = 10:00 
# probing interval in seconds
interval = 60

[key]
# You can customize the function of the key, currently available functions are
# slider: oled display next page
# switch: fan turn on/off switch
# reboot, poweroff
# If you have any good suggestions for key functions, 
# please add an issue on https://setq.me/rockpi-penta
click = slider
twice = switch
press = none

[time]
# twice: maximum time between double clicking (seconds)
# press: long press time (seconds)
twice = 0.7
press = 1.8

[slider]
# Whether the oled auto display next page and the time interval (seconds)
auto = true
time = 10

[oled]
# Whether rotate the text of oled 180 degrees, whether use Fahrenheit
rotate = false
f-temp = false

[general]
# debug messages to journald
debug = false 

[mqtt]
host = localhost
port = 1883
username = 
password = 
